// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxriRk8FtZrmTjGV0ug7Je5PR_pE6-Zv4',
    appId: '1:467154557192:web:fd9850403457dc734a74bd',
    messagingSenderId: '467154557192',
    projectId: 'fcm4flutter-5f1de',
    authDomain: 'fcm4flutter-5f1de.firebaseapp.com',
    storageBucket: 'fcm4flutter-5f1de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpaAu7iV1SNqR4HAWnMOlQtLmjNUIMoNE',
    appId: '1:467154557192:android:f002049ea25e61244a74bd',
    messagingSenderId: '467154557192',
    projectId: 'fcm4flutter-5f1de',
    storageBucket: 'fcm4flutter-5f1de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgDcFZeMfRV8DuM2xjchbMogpOGaDustQ',
    appId: '1:467154557192:ios:4790ab891aa6213c4a74bd',
    messagingSenderId: '467154557192',
    projectId: 'fcm4flutter-5f1de',
    storageBucket: 'fcm4flutter-5f1de.firebasestorage.app',
    iosBundleId: 'com.flutter.fcm.fcmflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgDcFZeMfRV8DuM2xjchbMogpOGaDustQ',
    appId: '1:467154557192:ios:4790ab891aa6213c4a74bd',
    messagingSenderId: '467154557192',
    projectId: 'fcm4flutter-5f1de',
    storageBucket: 'fcm4flutter-5f1de.firebasestorage.app',
    iosBundleId: 'com.flutter.fcm.fcmflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxriRk8FtZrmTjGV0ug7Je5PR_pE6-Zv4',
    appId: '1:467154557192:web:c74121a6c26c14b04a74bd',
    messagingSenderId: '467154557192',
    projectId: 'fcm4flutter-5f1de',
    authDomain: 'fcm4flutter-5f1de.firebaseapp.com',
    storageBucket: 'fcm4flutter-5f1de.firebasestorage.app',
  );
}
